subdomains:

  ogonek:
    title:  "ОГБУ «Социально-реабилитационный центр для несовершеннолетних «Огонёк» г.Томск"
    path:   "/ru/departament/podvedomstvennye-uchrezhdeniya/ogbu-tsentr-sotsialnoy-pomoschi-semie-i-detyam-ogonek-g-tomska-"

  friend:
    title:  "ОГБУ «Социально-реабилитационный центр для несовершеннолетних «Друг» г.Томск"
    path:   "/ru/departament/podvedomstvennye-uchrezhdeniya/ogbu-sotsialno-reabilitatsionnyy-tsentr-dlya-nesovershennoletnih-drug-g-tomska"

  luch:
    title:  "ОГБУ «Социально-реабилитационный центр для несовершеннолетних «Луч» г.Томск"
    path:   "/ru/departament/podvedomstvennye-uchrezhdeniya/ogbu-sotsialno-reabilitatsionnyy-tsentr-dlya-nesovershennoletnih-luch-g-tomska"

  zdorovie:
    title:  "ОГБУ «Центр детского и семейного отдыха «Здоровье»"
    :path:  "/ru/departament/podvedomstvennye-uchrezhdeniya/ogbu-tsentr-detskogo-i-semeynogo-otdyha-zdorovie-"

  srcntomsk:
    title:  "ОГКУ «Социально-реабилитационный центр для несовершеннолетних Томского района»"
    path:   "/ru/departament/podvedomstvennye-uchrezhdeniya/ogku-sotsialno-reabilitatsionnyy-tsentr-dlya-nesovershennoletnih-tomskogo-rayona-"

  srcnasino:
    title:  "ОГКУ «Социально-реабилитационный центр для несовершеннолетних Асиновского района»"
    path:   "/ru/departament/podvedomstvennye-uchrezhdeniya/ogku-sotsialno-reabilitatsionnyy-tsentr-dlya-nesovershennoletnih-asinovskogo-rayona-"

  srcnalx:
    title:  "ОГКУ «Социально-реабилитационный центр для несовершеннолетних «Александровского района»"
    path:   "/ru/departament/podvedomstvennye-uchrezhdeniya/ogku-sotsialno-reabilitatsionnyy-tsentr-dlya-nesovershennoletnih-aleksandrovskogo-rayona-"

  srcnkg:
    title:  "ОГКУ «Социально-реабилитационный центр для несовершеннолетних Каргасокского района»"
    path:   "/ru/departament/podvedomstvennye-uchrezhdeniya/ogku-sotsialno-reabilitatsionnyy-tsentr-dlya-nesovershennoletnih-kargasokskogo-rayona-"

  srcnklp:
    title:  "ОГКУ «Центр социальной помощи семье и детям Колпашевского района»"
    path:   "/ru/departament/podvedomstvennye-uchrezhdeniya/ogku-tsentr-sotsialnoy-pomoschi-semie-i-detyam-kolpashevskogo-rayona-"

  srcnkr:
    title:  "ОГКУ «Социально-реабилитационный центр для несовершеннолетних Кривошеинского района»"
    path:   "/ru/departament/podvedomstvennye-uchrezhdeniya/ogku-sotsialno-reabilitatsionnyy-tsentr-dlya-nesovershennoletnih-krivosheinskogo-rayona-"

  srcnmol:
    title:  "ОГКУ «Социально-реабилитационный центр для несовершеннолетних Молчановского района»"
    path:   "/ru/departament/podvedomstvennye-uchrezhdeniya/ogku-sotsialno-reabilitatsionnyy-tsentr-dlya-nesovershennoletnih-molchanovskogo-rayona-"

  srcnpar:
    title:  "ОГКУ «Социально-реабилитационный центр для несовершеннолетних Парабельского района»"
    path:   "/ru/departament/podvedomstvennye-uchrezhdeniya/ogku-sotsialno-reabilitatsionnyy-tsentr-dlya-nesovershennoletnih-parabelskogo-rayona-"

  srcnch:
    title:  "ОГКУ «Социально-реабилитационный центр для несовершеннолетних Чаинского района»"
    path:   "/ru/departament/podvedomstvennye-uchrezhdeniya/ogku-sotsialno-reabilitatsionnyy-tsentr-dlya-nesovershennoletnih-chainskogo-rayona-"

  srcnorl:
    title:  "ОГКОУ для детей-сирот и детей, оставшихся безпопечения родителей детский дом «Орлиное гнездо»"
    path:   "/ru/departament/podvedomstvennye-uchrezhdeniya/ogkou-dlya-detey-sirot-i-detey-ostavshihsya-bez-popecheniya-roditeley-detskiy-dom-orlinoe-gnezdo-"

  dd1:
    title:  "ТОГКОУ Специальный (коррекционный) детский дом №1 для детей-сирот, оставшихся без попечения родителей, с отклонениями в развитии»"
    path:   "/ru/departament/podvedomstvennye-uchrezhdeniya/togkou-spetsialnyy-korrektsionnyy-detskiy-dom-1-dlya-detey-sirot-i-detey-ostavshihsya-bez-popecheniya-roditeley-s-ogranichennymi-vozmozhnostyami-zdorovya-"

  dd4:
    title:  "ТОГКОУ для детей-сирот и детей, оставшихся без попечения родителей «детский дом №4»"
    path:   "/ru/departament/podvedomstvennye-uchrezhdeniya/togkou-dlya-detey-sirot-i-detey-ostavshihsya-bez-popecheniya-roditeley-detskiy-dom-4-"

  ddsem:
    title:  "ОГКОУ для детей-сирот и детей. оставшихся без попечения родителей «Семилуженский детский дом»"
    path:   "/ru/departament/podvedomstvennye-uchrezhdeniya/ogkou-dlya-detey-sirot-i-detey-ostavshihsya-bez-popecheniya-roditeley-semiluzhenskiy-detskiy-dom-"

  ddasino:
    title:  "ОГКОУ для детей-сирот и детей, оставшихся без попечения родителей «Асиновский детский дом»"
    path:   "/ru/departament/podvedomstvennye-uchrezhdeniya/ogkou-dlya-detey-sirot-i-detey-ostavshihsya-bez-popecheniya-roditeley-asinovskiy-detskiy-dom-"

  ddbk:
    title:  "ОГКОУ для детей-сирот и детей, оставшихся без попечения родителей «Бакчарский детский дом»"
    path:   "/ru/departament/podvedomstvennye-uchrezhdeniya/ogkou-dlya-detey-sirot-i-detey-ostavshihsya-bez-popecheniya-roditeley-bakcharskiy-detskiy-dom-"

  ddtg:
    title:  "ОГКОУ для детей сирот и детей, оставшихся без попечения родителей «Тогурский детский дом»"
    path:   "/ru/departament/podvedomstvennye-uchrezhdeniya/ogkou-dlya-detey-sirot-i-detey-ostavshihsya-bez-popecheniya-roditeley-togurskiy-detskiy-dom-"

  ddch:
    title:  "ОГКОУ для детей-сирот и детей, оставшихся без попечения родителей «Чердатский детский дом»"
    path:   "/ru/departament/podvedomstvennye-uchrezhdeniya/ogkou-dlya-detey-sirot-i-detey-ostavshihsya-bez-popecheniya-roditeley-cherdatskiy-detskiy-dom-"

  ddz:
    title:  "ОГКОУ для детей –сирот и детей, ставшихся без попечения родителей «Зырянский детский дом»"
    path:   "/ru/departament/podvedomstvennye-uchrezhdeniya/ogkou-dlya-detey-sirot-i-detey-ostavshihsya-bez-popecheniya-roditeley-zyryanskiy-detskiy-dom-"

  nadejda:
    title:  "ОГКСУ «Реабилитационный центр для детей и подростков с ограниченными возможностями «Надежда»"
    path:   "/ru/departament/podvedomstvennye-uchrezhdeniya/ogksu-reabilitatsionnyy-tsentr-dlya-detey-i-podrostkov-s-ogranichennymi-vozmozhnostyami-nadezhda-"

  csps:
    title:  "ОГБУ «ЦСП г.Стрежевой»"
    path:   "/ru/departament/podvedomstvennye-uchrezhdeniya/ogbu-tsentr-sotsialnoy-pomoschi-semie-i-detyam-g-strezhevogo-"

  rcs:
    title:  "ОГКУ «Реабилитационный центр для детей и подростков с ограниченными возможностями ЗАТО «Северск»"
    path:   "/ru/departament/podvedomstvennye-uchrezhdeniya/ogku-reabilitatsionnyy-tsentr-dlya-detey-i-podrostkov-s-ogranichennymi-vozmozhnostyami-zato-seversk-"

  ddt:
    title:  "ОГКСУ для умственно-отсталых детей «Тунгусовский детский дом-интернат»"
    path:   "/ru/departament/podvedomstvennye-uchrezhdeniya/ogksu-dlya-umstvenno-otstalyh-detey-tungusovskiy-detskiy-dom-internat-"
